version: "3"
services:
  pg_master:
    build: ./master
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=demkom58
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=demkom58
      - PG_REP_USER=rep
      - PG_REP_PASSWORD=123456
    networks:
      default:
        aliases:
          - pg_cluster
    ports:
      - 5000:5432
    restart: always
  pg_slave:
    build: ./slave
    environment:
      - POSTGRES_USER=demkom58
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=demkom58
      - PG_REP_USER=rep
      - PG_REP_PASSWORD=123456
      - PG_MASTER_HOST=pg_master
    networks:
      default:
        aliases:
          - pg_cluster
    ports:
      - 5001:5432
    restart: always
volumes:
  pg_data: